// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vknsdopeciudowssllba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrbnNkb3BlY2l1ZG93c3NsbGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTU4MDMsImV4cCI6MjA2MDQ5MTgwM30.pGv4QV74fl1fni3f5A6f2sUJlVJkqJg_WdDwTTgNXAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);